import json
import requests
import argparse
import sys
import os
import re
from colorama import init, deinit, Fore, Back, Style

URL = "https://www.ceskatelevize.cz/teletext-api/v2/text/"

def print_verbose(msg):
    if args.verbose:
        print(msg)

def parse_args():
    global args
    parser = argparse.ArgumentParser(
        prog="CT Teletext Viewer",
        description="Viewer for Česká Televize (ČT) teletext. All arguments are optional.")
    parser.add_argument('-p', '--page', type=str, help="go to a specific page")
    parser.add_argument('-s', '--subpage', type=str, help="go to a specific subpage")
    parser.add_argument('--disable-colors', action='store_true', help="disable colors in output")
    parser.add_argument('--verbose', action='store_true', help="explain what is being done")

    args = parser.parse_args()

    args_num = len(sys.argv)

    if args.page:
        get_teletext_json(URL)
        print(get_teletext_page(args.page, args.subpage))
        sys.exit()

def get_teletext_json(url):
    global pages
    global json_teletext

    print_verbose("Downloading teletext...")
    r = requests.get(url)
    json_teletext = json.loads(r.text)
    pages = list(json_teletext["data"].keys())

def get_teletext_page(page_num, subpage=None):
    print_verbose("Parsing teletext content and applying formatting...")
    global subpages
    if subpage is None: # true if no page was provided
        try:
            subpages = json_teletext["data"][page_num]["subpages"]
        except KeyError:
            print(f"Page {page_num} doesn't exist. Try to go to page 100.")
            return " "

        if not subpages:
            # page doesn't have any subpages, print the only page
            return get_teletext_page(page_num, "")
        else:
            print_verbose(f"No subpage provided, printing default {current_subpage} subpage.")
            return get_teletext_page(page_num, current_subpage)
    else:
        try:
            output = json_teletext["data"][page_num]["text"][page_num + subpage][5:-6] # parse page from json and strip <pre> tag (with [5:-6])
        except KeyError:
            print(f"Subpage {subpage} doesn't exist for page {page_num}.")
            return " "

        # skip colorizing output
        if args.disable_colors:
            return output

        # COLORIZING

        lines = output.split("\n")

        # colorize a title if there is any
        if lines[0].isspace() and not lines[1].isspace() and lines[2].isspace():
            lines[1] = f"{Fore.CYAN}{lines[1]}{Style.RESET_ALL}" # title
            lines[0] = f"{Fore.BLUE}{'─'*40}{Style.RESET_ALL}"
            lines[2] = f"{Fore.BLUE}{'─'*40}{Style.RESET_ALL}"

        output = "\n".join(lines)

        # select 3 digit number or 1/2 digit number with dash before it
        pattern = r'(?<!\d)(\d{3})(?=\D|$)|(?<=-)(\d{1,2})(?=\D|$)' # this regex was generated by ChatGPT, because I would never have figured that out
        output = re.sub(pattern, r'{}\g<0>{}'.format(Fore.LIGHTCYAN_EX, Style.RESET_ALL), output)
        
        return output

def print_menu(current_page):
    # print list of subpages
    print("Subpages:       ", end=" ")
    if subpages:
        for subpage in subpages:
            if subpage == current_subpage: # print current subpage in color
                print(f"{Fore.LIGHTBLACK_EX}{subpage:^3}", end=" ")
            else:
                print(f"{subpage:^3}", end=" ")
        print("")
    else:
        print() # put cursor to newline

    # print list of 7 nearby pages
    if current_page in pages: # 
        index = pages.index(current_page)
    else:
        index = 0

    num_pages = len(pages)

    if index <= 3:
        near_pages = range(0, 7)  # select first 7 pages
    elif index >= num_pages - 4:
        near_pages = range(num_pages - 7, num_pages) # select last 7 pages
    else:
        near_pages = range(index - 3, index + 4) # select previous 3, current and next 3 pages
    
    print("Pages:          ", end=" ")
    for near_page in near_pages:
        if index == near_page:  # print current page in color
            print(f"{Fore.LIGHTBLACK_EX}{pages[near_page]}", end=" ")
        else:
            print(pages[near_page], end=" ")
    print() # put cursor to new line

init(autoreset=True)

current_page = "100"
current_subpage = 'A'

parse_args()
get_teletext_json(URL)

while True:
    os.system('cls' if os.name == 'nt' else 'clear')

    print(get_teletext_page(current_page))
    
    print_verbose("Displaying navigation menu...")
    print_menu(current_page)

    print_verbose("Waiting for user input...")
    user_input = input("Page or Subpage: ")

    current_subpage = 'A'

    if user_input.isnumeric():
        current_page = user_input
    else:
        current_subpage = user_input.capitalize()

deinit()
